spring:
  application:
    name: auth-boilerplate
  datasource:
    url: jdbc:postgresql://localhost:5434/auth_boilerplate_dev
    username: admin
    password: 412i08926g45ehfR

springdoc:
  swagger-ui:
    path: /api/docs
    operationsSorter: method
    disable-swagger-default-url: true
    doc-expansion: none
  api-docs:
    path: /api/docs/json